[package]
name = "tessari-s3-infrastructure"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
tessari-s3-constants.workspace = true
tessari-s3-types.workspace = true
tessari-s3-observability.workspace = true
thiserror.workspace = true
tessaridb-client.workspace = true
tokio = { workspace = true, features = ["sync", "time"] }
tracing.workspace = true
reqwest.workspace = true
bytes.workspace = true
futures-util.workspace = true

[lints]
workspace = true
