[package]
name = "tessari-s3-node"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "tessaridb-s3"
path = "src/main.rs"

[dependencies]
tessari-s3-observability.workspace = true
tessari-s3-infrastructure.workspace = true
tessari-s3-api.workspace = true
tessari-s3-storage.workspace = true
tessari-s3-daemons.workspace = true
axum.workspace = true
tokio = { workspace = true, features = ["net", "time", "sync"] }
tracing.workspace = true
anyhow.workspace = true

[dev-dependencies]
tessari-s3-types.workspace = true
tokio = { workspace = true, features = ["process", "net", "time"] }
reqwest.workspace = true
hmac.workspace = true
sha2.workspace = true
uuid.workspace = true
tessaridb-client.workspace = true
rcgen.workspace = true
bytes.workspace = true
futures-util.workspace = true

[lints]
workspace = true
