"""Generate the operation catalog from the AWS S3 service model.

Usage:
    python3 scripts/catalog/generate_catalog.py <service-2.json>          # rewrite catalog.rs
    python3 scripts/catalog/generate_catalog.py <service-2.json> --check  # exit 1 if catalog.rs differs

The model is the S3 `service-2.json` (API version 2006-03-01) shipped with every AWS SDK. Re-run on every SDK
upgrade: an operation present in the model and absent here is an operation the dispatcher has no answer for.
"""
import hashlib
import json
import pathlib
import sys

OUT = pathlib.Path(__file__).resolve().parents[2] / "crates/tessari-s3-core/src/dispatch/catalog.rs"

# Operations that share their whole wire shape with another and are answered by it: the deprecated twins (the model
# marks them) and ListDirectoryBuckets, which differs from ListBuckets only by the endpoint type it is sent to.
SHADOWED_BY_ENDPOINT = {"ListDirectoryBuckets"}


def target_of(uri):
    path = uri.split("?", 1)[0]
    if path == "/":
        return "Service"
    if path == "/{Bucket}":
        return "Bucket"
    if path == "/{Bucket}/{Key+}":
        return "Object"
    return f'Named("{path}")'


def discriminators_of(uri):
    if "?" not in uri:
        return []
    out = []
    for part in uri.split("?", 1)[1].split("&"):
        name, _, value = part.partition("=")
        out.append((name, value or None))
    return out


def rust_strs(items):
    return "&[" + ", ".join(f'"{item}"' for item in items) + "]"


def render(model_bytes):
    model = json.loads(model_bytes)
    operations, shapes = model["operations"], model["shapes"]
    digest = hashlib.sha256(model_bytes).hexdigest()
    names = sorted(operations)
    enum_lines, rows = [], []
    for name in names:
        op = operations[name]
        http = op["http"]
        query, required_query, required_headers = [], [], []
        input_shape = op.get("input", {}).get("shape")
        if input_shape:
            shape = shapes[input_shape]
            required = set(shape.get("required", []))
            for member, spec in shape.get("members", {}).items():
                location = spec.get("location")
                if location == "querystring":
                    query.append(spec["locationName"])
                    if member in required:
                        required_query.append(spec["locationName"])
                elif location == "header" and member in required:
                    required_headers.append(spec["locationName"].lower())
        discriminators = "&[" + ", ".join(
            f'("{n}", {"Some(" + chr(34) + v + chr(34) + ")" if v else "None"})' for n, v in discriminators_of(http["requestUri"])
        ) + "]"
        dispatchable = not op.get("deprecated", False) and name not in SHADOWED_BY_ENDPOINT
        enum_lines.append(f"    {name},")
        rows.append(
            f'    OperationSpec {{ operation: Operation::{name}, name: "{name}", method: Method::{http["method"].title()}, '
            f'target: Target::{target_of(http["requestUri"])}, discriminators: {discriminators}, '
            f"required_query: {rust_strs(sorted(required_query))}, required_headers: {rust_strs(sorted(required_headers))}, "
            f"query: {rust_strs(sorted(query))}, dispatchable: {str(dispatchable).lower()} }},"
        )
    header = (
        "//! GENERATED by `scripts/catalog/generate_catalog.py` from the AWS S3 service model (`service-2.json`, API\n"
        f"//! version 2006-03-01, sha256 `{digest[:16]}…`, {len(names)} operations). Do not edit: re-run the script, and\n"
        "//! run it with `--check` after every SDK upgrade.\n\n"
        "use super::spec::{Method, OperationSpec, Target};\n\n"
    )
    enum = (
        "/// Every operation of the S3 API model.\n"
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]\n"
        "#[allow(\n"
        "    missing_docs,\n"
        "    reason = \"each variant is the operation of the same name in the S3 API model\"\n"
        ")]\n"
        "pub enum Operation {\n" + "\n".join(enum_lines) + "\n}\n\n"
    )
    table = (
        f"/// The catalog, one row per operation of the model, sorted by name.\n#[rustfmt::skip]\n"
        f"pub const CATALOG: [OperationSpec; {len(names)}] = [\n" + "\n".join(rows) + "\n];\n"
    )
    return header + enum + table


def main():
    model_bytes = pathlib.Path(sys.argv[1]).read_bytes()
    rendered = render(model_bytes)
    if "--check" in sys.argv[2:]:
        current = OUT.read_text() if OUT.exists() else ""
        if current != rendered:
            print(f"{OUT} differs from the model; re-run without --check", file=sys.stderr)
            sys.exit(1)
        print(f"{OUT.name} matches the model")
        return
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(rendered)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
